/**
 * Prova de resultados — dados espelhados da planilha (Fev + início Mar).
 * Dados espelhados da planilha; edite aqui quando houver novos meses/linhas.
 */
import type {
  DiarioFooter,
  MesResultadoKey,
  MesSelecao,
  ResumoDiario,
  ResumoEstrategia,
  ResumoMesConfig,
  ResultadoTrade,
  StrategyCol,
} from "./resultados-types";

/** Valores de PnL e resumos na planilha assumem este risco por trade (USD). */
export const TARGET_LOSS_BASE_USD = 25;

export const RESULTADOS_META = {
  targetLossUsd: TARGET_LOSS_BASE_USD,
  dolarBrlFev: 5.2,
  dolarBrlMar: 5.2,
};

export const RESUMO_FEV: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 118.4, winRatePct: 78.95, ranking: 4, lucroBrl: 615.7 },
  { nome: "MEDIANO", lucroUsd: 209.09, winRatePct: 68.42, ranking: 3, lucroBrl: 1087.28 },
  { nome: "AGRESSIVO", lucroUsd: 450.79, winRatePct: 52.63, ranking: 2, lucroBrl: 2344.12 },
  { nome: "DEGEN", lucroUsd: 679.29, winRatePct: 42.11, ranking: 1, lucroBrl: 3532.31 },
];

export const RESUMO_MAR: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 1016.59, winRatePct: 74.16, ranking: 4, lucroBrl: 5286.28 },
  { nome: "MEDIANO", lucroUsd: 1413.4, winRatePct: 60.67, ranking: 3, lucroBrl: 7349.68 },
  { nome: "AGRESSIVO", lucroUsd: 2567.83, winRatePct: 47.19, ranking: 2, lucroBrl: 13352.7 },
  { nome: "DEGEN", lucroUsd: 2951.1, winRatePct: 31.46, ranking: 1, lucroBrl: 15345.71 },
];

/** Diário — Fevereiro (planilha). */
export const RESUMO_FEV_DIARIO: ResumoDiario[] = [
  { nome: "Conservador", diasLucro: 10, diasPrejuizo: 2, diasLucroPct: 83, mediaDiariaUsd: 9.87, mediaDiariaBrl: 51.31 },
  { nome: "Mediano", diasLucro: 9, diasPrejuizo: 3, diasLucroPct: 75, mediaDiariaUsd: 17.42, mediaDiariaBrl: 90.61 },
  { nome: "Agressivo", diasLucro: 8, diasPrejuizo: 4, diasLucroPct: 67, mediaDiariaUsd: 37.57, mediaDiariaBrl: 195.34 },
  { nome: "Degen", diasLucro: 6, diasPrejuizo: 6, diasLucroPct: 50, mediaDiariaUsd: 56.61, mediaDiariaBrl: 294.36 },
];

export const RESUMO_FEV_DIARIO_FOOTER: DiarioFooter = {
  diasLucroPct: 69,
  mediaDiariaUsd: 30.37,
  mediaDiariaBrl: 157.9,
};

const dMar = RESULTADOS_META.dolarBrlMar;

/** Diário — Março. */
export const RESUMO_MAR_DIARIO: ResumoDiario[] = [
  { nome: "Conservador", diasLucro: 17, diasPrejuizo: 10, diasLucroPct: 63, mediaDiariaUsd: 182.29 / dMar, mediaDiariaBrl: 182.29 },
  { nome: "Mediano", diasLucro: 19, diasPrejuizo: 8, diasLucroPct: 70, mediaDiariaUsd: 253.44 / dMar, mediaDiariaBrl: 253.44 },
  { nome: "Agressivo", diasLucro: 16, diasPrejuizo: 11, diasLucroPct: 59, mediaDiariaUsd: 460.44 / dMar, mediaDiariaBrl: 460.44 },
  { nome: "Degen", diasLucro: 14, diasPrejuizo: 13, diasLucroPct: 52, mediaDiariaUsd: 529.16 / dMar, mediaDiariaBrl: 529.16 },
];

export const RESUMO_MAR_DIARIO_FOOTER: DiarioFooter = {
  diasLucroPct: Math.round(
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.diasLucroPct, 0) / RESUMO_MAR_DIARIO.length,
  ),
  mediaDiariaUsd:
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.mediaDiariaUsd, 0) / RESUMO_MAR_DIARIO.length,
  mediaDiariaBrl:
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.mediaDiariaBrl, 0) / RESUMO_MAR_DIARIO.length,
};

/** Meses com dados (ordem de exibição após Agregado). */
export const MESES_RESULTADO_ORDEM: MesResultadoKey[] = ["MAR", "FEV"];

export const SELECAO_MESES_ORDEM: MesSelecao[] = ["AGG", ...MESES_RESULTADO_ORDEM];

export const ROTULO_SELECAO_MES: Record<MesSelecao, string> = {
  AGG: "Agregado",
  FEV: "Fevereiro",
  MAR: "Março",
};

export const RESUMO_POR_MES: Record<MesResultadoKey, ResumoMesConfig> = {
  FEV: {
    estrategias: RESUMO_FEV,
    diario: RESUMO_FEV_DIARIO,
    diarioFooter: RESUMO_FEV_DIARIO_FOOTER,
  },
  MAR: {
    estrategias: RESUMO_MAR,
    diario: RESUMO_MAR_DIARIO,
    diarioFooter: RESUMO_MAR_DIARIO_FOOTER,
  },
};

const S = (hit: StrategyCol["hit"], pnlUsd: number | null): StrategyCol => ({ hit, pnlUsd });

const allStop25 = (): Pick<
  ResultadoTrade,
  "conservador" | "mediano" | "agressivo" | "degen"
> => ({
  conservador: S("STOP", -25),
  mediano: S("STOP", -25),
  agressivo: S("STOP", -25),
  degen: S("STOP", -25),
});

type StratPick = Pick<ResultadoTrade, "conservador" | "mediano" | "agressivo" | "degen">;

/** Alvo 1 — quatro estratégias (planilha). */
const winT1: StratPick = {
  conservador: S("1", 0.56),
  mediano: S("1", 0.6),
  agressivo: S("1", 0.71),
  degen: S("1", 0.68),
};

/** Alvo 2 — quatro estratégias. */
const winT2: StratPick = {
  conservador: S("2", 12.72),
  mediano: S("2", 25.23),
  agressivo: S("2", 36.17),
  degen: S("2", 68.16),
};

/** Alvo 3 — quatro estratégias. */
const winT3: StratPick = {
  conservador: S("3", 31.14),
  mediano: S("3", 56.08),
  agressivo: S("3", 113.17),
  degen: S("3", 204.15),
};

/** Alvo 2 no conservador; mediano STOP; restantes alvo 2 (padrão AAVE Fev). */
const winT2MedStop: StratPick = {
  conservador: S("2", 21.11),
  mediano: S("STOP", -25),
  agressivo: S("2", 36.17),
  degen: S("STOP", -25),
};

/** Alvo 1 no conservador com $0,63; demais STOP (padrão SUI Fev). */
const winT1c063RestStop: StratPick = {
  conservador: S("1", 0.63),
  mediano: S("STOP", -25),
  agressivo: S("STOP", -25),
  degen: S("STOP", -25),
};

/** PnL USD por estratégia exatamente como na planilha (hit para exibição). */
function pn(c: number, m: number, a: number, d: number): StratPick {
  const hitOf = (v: number): StrategyCol["hit"] => {
    if (v <= -24.5) return "STOP";
    if (
      Math.abs(v - 31.14) < 0.02 ||
      Math.abs(v - 56.08) < 0.02 ||
      Math.abs(v - 113.17) < 0.02 ||
      Math.abs(v - 204.15) < 0.02
    )
      return "3";
    if (
      Math.abs(v - 12.72) < 0.02 ||
      Math.abs(v - 25.23) < 0.02 ||
      Math.abs(v - 36.17) < 0.02 ||
      Math.abs(v - 68.16) < 0.02 ||
      Math.abs(v - 21.11) < 0.02
    )
      return "2";
    return "1";
  };
  return {
    conservador: S(hitOf(c), c),
    mediano: S(hitOf(m), m),
    agressivo: S(hitOf(a), a),
    degen: S(hitOf(d), d),
  };
}

export const RESULTADOS_TRADES: ResultadoTrade[] = [
  // —— Fevereiro (planilha FEVEREIRO) ——
  {
    id: 1,
    mes: "FEV",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "09/02",
    stop: -1.95,
    alvo: 0,
    motivos: "-",
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 2,
    mes: "FEV",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "10/02",
    stop: -1.51,
    alvo: 0,
    motivos: "-",
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 3,
    mes: "FEV",
    symbol: "BTC",
    tf: "30m",
    side: "SHORT",
    dataLabel: "21/02",
    stop: -0.95,
    alvo: 3,
    motivos: "-",
    conservador: S("2", 12.72),
    mediano: S("2", 25.23),
    agressivo: S("2", 36.17),
    degen: S("2", 68.16),
  },
  {
    id: 4,
    mes: "FEV",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 18,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 5,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "12/02",
    stop: -1.05,
    alvo: 18,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 6,
    mes: "FEV",
    symbol: "BTC",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 1.618,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 7,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "13/02",
    stop: -1.5,
    alvo: 0.618,
    motivos: "-",
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 8,
    mes: "FEV",
    symbol: "AAVE",
    tf: "30m",
    side: "LONG",
    dataLabel: "19/02",
    stop: -2.6,
    alvo: 2.4,
    motivos: "-",
    conservador: S("2", 21.11),
    mediano: S("STOP", -25),
    agressivo: S("2", 36.17),
    degen: S("STOP", -25),
  },
  {
    id: 9,
    mes: "FEV",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -0.618,
    alvo: 1,
    motivos: "-",
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("1", 0.71),
    degen: S("1", 0.68),
  },
  {
    id: 10,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "18/02",
    stop: -1.25,
    alvo: 2.4,
    motivos: "-",
    conservador: S("2", 12.72),
    mediano: S("2", 25.23),
    agressivo: S("2", 36.17),
    degen: S("STOP", -25),
  },
  {
    id: 11,
    mes: "FEV",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -1.45,
    alvo: 0.618,
    motivos: "-",
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 12,
    mes: "FEV",
    symbol: "UNI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "20/02",
    stop: -0.8,
    alvo: 1,
    motivos: "-",
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("1", 0.71),
    degen: S("1", 0.68),
  },
  {
    id: 13,
    mes: "FEV",
    symbol: "BTC",
    tf: "1h",
    side: "SHORT",
    dataLabel: "22/02",
    stop: -0.94,
    alvo: 9,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 14,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "22/02",
    stop: -2.4,
    alvo: -0.618,
    motivos: "-",
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 15,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.414,
    alvo: 0.618,
    motivos: "-",
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 16,
    mes: "FEV",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.06,
    alvo: 10,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 17,
    mes: "FEV",
    symbol: "LINK",
    tf: "15m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -1.2,
    alvo: 13.5,
    motivos: "-",
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("STOP", -25),
  },
  {
    id: 18,
    mes: "FEV",
    symbol: "ADA",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0,
    motivos: "-",
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 19,
    mes: "FEV",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0.618,
    motivos: "-",
    conservador: S("1", 0.63),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },

  // —— Março início (planilha MARÇO) ——
  {
    id: 20,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "01/03",
    stop: -1.87,
    alvo: 0.9,
    motivos: "FR/FO",
    ...pn(0.63, 1.14, 0.71, 0.68),
  },
  {
    id: 21,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -1.83,
    alvo: 0.2,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 22,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.32,
    alvo: 0.7,
    motivos: "LSR",
    ...pn(0.63, 1.14, -25, -25),
  },
  {
    id: 23,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.15,
    alvo: 0.7,
    motivos: "FR/FO",
    ...pn(0.63, 1.14, -25, -25),
  },
  {
    id: 24,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.48,
    alvo: 0.1,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 25,
    mes: "MAR",
    symbol: "BTC",
    tf: "4h",
    side: "SHORT",
    dataLabel: "02/03",
    stop: -0.618,
    alvo: 1.5,
    motivos: "LSR",
    ...pn(0.56, 0.6, 0.71, 0.68),
  },
  {
    id: 26,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.21,
    alvo: 1.3,
    motivos: "LSR",
    ...pn(0.56, 0.6, 0.71, 0.68),
  },
  {
    id: 27,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.19,
    alvo: -0.4,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 28,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.5,
    alvo: 2.4,
    motivos: "LE/HE",
    ...pn(12.72, 25.23, 36.17, 68.16),
  },
  {
    id: 29,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "03/03",
    stop: -0.618,
    alvo: 2.2,
    motivos: "-",
    ...pn(12.72, 25.23, 36.17, 68.16),
  },

  {
    id: 30,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.59,
    alvo: 0.6,
    motivos: "-",
    ...pn(0.56, 0.6, -25, -25),
  },
  {
    id: 31,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -2.35,
    alvo: 0.9,
    motivos: "-",
    ...pn(0.63, -25, -25, -25),
  },
  {
    id: 32,
    mes: "MAR",
    symbol: "BTC",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -2.05,
    alvo: -0.4,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 33,
    mes: "MAR",
    symbol: "AAVE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.32,
    alvo: 1.6,
    motivos: "LSR",
    ...pn(12.72, 25.23, 36.17, 68.16),
  },
  {
    id: 34,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.7,
    alvo: 1.0,
    motivos: "-",
    ...pn(0.56, 0.6, -25, -25),
  },
  {
    id: 35,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.7,
    alvo: 6.5,
    motivos: "FR/FO",
    ...pn(31.14, 56.08, 113.17, 204.15),
  },
  {
    id: 36,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.8,
    alvo: 7.1,
    motivos: "-",
    ...pn(31.14, 56.08, 113.17, 204.15),
  },
  {
    id: 37,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.618,
    alvo: 5.4,
    motivos: "-",
    ...pn(31.14, 56.08, 113.17, 204.15),
  },
  {
    id: 38,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "04/03",
    stop: -2.48,
    alvo: -0.1,
    motivos: "-",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 39,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "05/03",
    stop: -1.3,
    alvo: 1.6,
    motivos: "-",
    ...pn(12.72, 25.23, 36.17, 68.16),
  },
  {
    id: 40,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "SHORT",
    dataLabel: "05/03",
    stop: -0.7,
    alvo: 5.1,
    motivos: "-",
    ...pn(31.14, 56.08, 113.17, 204.15),
  },
  {
    id: 41,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.7,
    alvo: -0.6,
    motivos: "LE/HE",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 42,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -0.618,
    alvo: 2.3,
    motivos: "LE/HE",
    ...pn(12.72, 25.23, 36.17, 68.16),
  },
  {
    id: 43,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.414,
    alvo: -0.3,
    motivos: "LE/HE",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 44,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.59,
    alvo: -0.5,
    motivos: "FR/FO",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 45,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -2.11,
    alvo: -0.5,
    motivos: "LE/HE",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 46,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -1.52,
    alvo: 0,
    motivos: "-",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 47,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -2.3,
    alvo: 1.5,
    motivos: "FR/FO",
    ...pn(21.11, -25, -25, -25),
  },

  {
    id: 48,
    mes: "MAR",
    symbol: "LINK",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 49,
    mes: "MAR",
    symbol: "ADA",
    tf: "30m",
    side: "LONG",
    dataLabel: "07/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...allStop25(),
  },
  {
    id: 50,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "07/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...allStop25(),
  },
  {
    id: 51,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "07/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT2MedStop,
  },
  {
    id: 52,
    mes: "MAR",
    symbol: "AAVE",
    tf: "30m",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 53,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 54,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 55,
    mes: "MAR",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 56,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1,
  },
  {
    id: 57,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT2,
  },
  {
    id: 58,
    mes: "MAR",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 59,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 60,
    mes: "MAR",
    symbol: "BNB",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 61,
    mes: "MAR",
    symbol: "ETH",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 62,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 63,
    mes: "MAR",
    symbol: "SOL",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 64,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "09/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...allStop25(),
  },
  {
    id: 65,
    mes: "MAR",
    symbol: "AAVE",
    tf: "4h",
    side: "LONG",
    dataLabel: "09/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT2,
  },
  {
    id: 66,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "SHORT",
    dataLabel: "10/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT2,
  },
  {
    id: 67,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "10/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT1c063RestStop,
  },
  {
    id: 68,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "10/03",
    stop: -0.7,
    alvo: 0.8,
    motivos: "LE/HE",
    ...winT1,
  },
  {
    id: 69,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/03",
    stop: -1.86,
    alvo: 1.9,
    motivos: "LSR",
    ...winT2MedStop,
  },
  {
    id: 70,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "11/03",
    stop: -0.7,
    alvo: 11.3,
    motivos: "-",
    ...winT3,
  },
  {
    id: 71,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -2.9,
    alvo: -0.6,
    motivos: "-",
    ...allStop25(),
  },
  {
    id: 72,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -1.075,
    alvo: 0.6,
    motivos: "LSR",
    ...winT1,
  },
  {
    id: 73,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -0.94,
    alvo: 1.5,
    motivos: "LSR",
    ...winT1,
  },
  {
    id: 74,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -0.618,
    alvo: 1.7,
    motivos: "LSR",
    ...winT2,
  },

  {
    id: 75,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -2.11,
    alvo: 0.6,
    motivos: "FR/FO",
    ...pn(0.63, 1.14, 0.71, 0.68),
  },
  {
    id: 76,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -2.32,
    alvo: -0.8,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 77,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -3.42,
    alvo: 1.2,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 78,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -3.41,
    alvo: 1.2,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 79,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -5.6,
    alvo: 2.1,
    motivos: "-",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 80,
    mes: "MAR",
    symbol: "XRP",
    tf: "30m",
    side: "SHORT",
    dataLabel: "13/03",
    stop: -2.75,
    alvo: 2.0,
    motivos: "LSR",
    ...winT2MedStop,
  },
  {
    id: 81,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "14/03",
    stop: -1.38,
    alvo: 1.0,
    motivos: "FR/FO",
    ...winT1,
  },
  {
    id: 82,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "15/03",
    stop: -1.32,
    alvo: 12.0,
    motivos: "LE/HE",
    ...winT3,
  },
  {
    id: 83,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -7,
    alvo: null,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 84,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -6,
    alvo: null,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 85,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -10,
    alvo: null,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 86,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.72,
    alvo: 10.4,
    motivos: "LE/HE",
    ...winT3,
  },
  {
    id: 87,
    mes: "MAR",
    symbol: "UNI",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.105,
    alvo: 4.7,
    motivos: "LE/HE",
    ...winT3,
  },
  {
    id: 88,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -0.62,
    alvo: 0.6,
    motivos: "-",
    ...winT1,
  },
  {
    id: 89,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -13.3,
    alvo: null,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 90,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.275,
    alvo: 3.4,
    motivos: "-",
    ...winT2,
  },
  {
    id: 91,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -2.035,
    alvo: 3.7,
    motivos: "LSR",
    ...winT2MedStop,
  },

  {
    id: 92,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 93,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...winT3,
  },
  {
    id: 94,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: null,
    alvo: null,
    motivos: "LSR",
    ...winT2MedStop,
  },
  {
    id: 95,
    mes: "MAR",
    symbol: "ADA",
    tf: "1h",
    side: "SHORT",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "LE/HE",
    ...winT3,
  },
  {
    id: 96,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "LSR",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 97,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "FR/FO",
    ...winT1,
  },
  {
    id: 98,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "-",
    ...pn(-25, -25, -25, -25),
  },
  {
    id: 99,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "LSR",
    ...winT3,
  },
  {
    id: 100,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "17/03",
    stop: null,
    alvo: null,
    motivos: "LSR",
    ...winT1,
  },
  {
    id: 101,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "SHORT",
    dataLabel: "18/03",
    stop: null,
    alvo: null,
    motivos: "FR/FO",
    ...winT2MedStop,
  },

];
