/**
 * Prova de resultados â€” dados espelhados da planilha (Fev + inÃ­cio Mar).
 * Dados espelhados da planilha; edite aqui quando houver novos meses/linhas.
 */
import type {
  DiarioFooter,
  MesResultadoKey,
  MesSelecao,
  ResumoDiario,
  ResumoEstrategia,
  ResumoMesConfig,
  ResultadoTrade,
  StrategyCol,
} from "./resultados-types";

/** Valores de PnL e resumos na planilha assumem este risco por trade (USD). */
export const TARGET_LOSS_BASE_USD = 25;

export const RESULTADOS_META = {
  targetLossUsd: TARGET_LOSS_BASE_USD,
  dolarBrlFev: 5.2,
  dolarBrlMar: 5.2,
};

export const RESUMO_FEV: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 118.4, winRatePct: 78.95, ranking: 4, lucroBrl: 615.7 },
  { nome: "MEDIANO", lucroUsd: 209.09, winRatePct: 68.42, ranking: 3, lucroBrl: 1087.28 },
  { nome: "AGRESSIVO", lucroUsd: 450.79, winRatePct: 52.63, ranking: 2, lucroBrl: 2344.12 },
  { nome: "DEGEN", lucroUsd: 679.29, winRatePct: 42.11, ranking: 1, lucroBrl: 3532.31 },
];

export const RESUMO_MAR: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 1016.59, winRatePct: 74.16, ranking: 4, lucroBrl: 5286.28 },
  { nome: "MEDIANO", lucroUsd: 1413.4, winRatePct: 60.67, ranking: 3, lucroBrl: 7349.68 },
  { nome: "AGRESSIVO", lucroUsd: 2567.83, winRatePct: 47.19, ranking: 2, lucroBrl: 13352.7 },
  { nome: "DEGEN", lucroUsd: 2951.1, winRatePct: 31.46, ranking: 1, lucroBrl: 15345.71 },
];

/** DiÃ¡rio â€” Fevereiro (planilha). */
export const RESUMO_FEV_DIARIO: ResumoDiario[] = [
  { nome: "Conservador", diasLucro: 10, diasPrejuizo: 2, diasLucroPct: 83, mediaDiariaUsd: 9.87, mediaDiariaBrl: 51.31 },
  { nome: "Mediano", diasLucro: 9, diasPrejuizo: 3, diasLucroPct: 75, mediaDiariaUsd: 17.42, mediaDiariaBrl: 90.61 },
  { nome: "Agressivo", diasLucro: 8, diasPrejuizo: 4, diasLucroPct: 67, mediaDiariaUsd: 37.57, mediaDiariaBrl: 195.34 },
  { nome: "Degen", diasLucro: 6, diasPrejuizo: 6, diasLucroPct: 50, mediaDiariaUsd: 56.61, mediaDiariaBrl: 294.36 },
];

export const RESUMO_FEV_DIARIO_FOOTER: DiarioFooter = {
  diasLucroPct: 69,
  mediaDiariaUsd: 30.37,
  mediaDiariaBrl: 157.9,
};

const dMar = RESULTADOS_META.dolarBrlMar;

/** DiÃ¡rio â€” MarÃ§o. */
export const RESUMO_MAR_DIARIO: ResumoDiario[] = [
  { nome: "Conservador", diasLucro: 17, diasPrejuizo: 10, diasLucroPct: 63, mediaDiariaUsd: 182.29 / dMar, mediaDiariaBrl: 182.29 },
  { nome: "Mediano", diasLucro: 19, diasPrejuizo: 8, diasLucroPct: 70, mediaDiariaUsd: 253.44 / dMar, mediaDiariaBrl: 253.44 },
  { nome: "Agressivo", diasLucro: 16, diasPrejuizo: 11, diasLucroPct: 59, mediaDiariaUsd: 460.44 / dMar, mediaDiariaBrl: 460.44 },
  { nome: "Degen", diasLucro: 14, diasPrejuizo: 13, diasLucroPct: 52, mediaDiariaUsd: 529.16 / dMar, mediaDiariaBrl: 529.16 },
];

export const RESUMO_MAR_DIARIO_FOOTER: DiarioFooter = {
  diasLucroPct: Math.round(
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.diasLucroPct, 0) / RESUMO_MAR_DIARIO.length,
  ),
  mediaDiariaUsd:
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.mediaDiariaUsd, 0) / RESUMO_MAR_DIARIO.length,
  mediaDiariaBrl:
    RESUMO_MAR_DIARIO.reduce((s, r) => s + r.mediaDiariaBrl, 0) / RESUMO_MAR_DIARIO.length,
};

/** Meses com dados (ordem de exibiÃ§Ã£o apÃ³s Agregado). */
export const MESES_RESULTADO_ORDEM: MesResultadoKey[] = ["MAR", "FEV"];

export const SELECAO_MESES_ORDEM: MesSelecao[] = ["AGG", ...MESES_RESULTADO_ORDEM];

export const ROTULO_SELECAO_MES: Record<MesSelecao, string> = {
  AGG: "Agregado",
  FEV: "Fevereiro",
  MAR: "MarÃ§o",
};

export const RESUMO_POR_MES: Record<MesResultadoKey, ResumoMesConfig> = {
  FEV: {
    estrategias: RESUMO_FEV,
    diario: RESUMO_FEV_DIARIO,
    diarioFooter: RESUMO_FEV_DIARIO_FOOTER,
  },
  MAR: {
    estrategias: RESUMO_MAR,
    diario: RESUMO_MAR_DIARIO,
    diarioFooter: RESUMO_MAR_DIARIO_FOOTER,
  },
};

// Queremos apenas os valores numÃ©ricos da tabela (PnL). O campo `hit` nÃ£o Ã© usado.
const S = (pnlUsd: number | null): StrategyCol => ({ hit: null, pnlUsd });

export const RESULTADOS_TRADES: ResultadoTrade[] = [
  // â€”â€” Fevereiro (planilha FEVEREIRO) â€”â€”
  {
    id: 1,
    mes: "FEV",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "09/02",
    stop: -1.95,
    alvo: 0,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 2,
    mes: "FEV",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "10/02",
    stop: -1.51,
    alvo: 0,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 3,
    mes: "FEV",
    symbol: "BTC",
    tf: "30m",
    side: "SHORT",
    dataLabel: "21/02",
    stop: -0.95,
    alvo: 3,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 4,
    mes: "FEV",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 18,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 5,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "12/02",
    stop: -1.05,
    alvo: 18,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 6,
    mes: "FEV",
    symbol: "BTC",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 1.618,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 7,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "13/02",
    stop: -1.5,
    alvo: 0.618,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 8,
    mes: "FEV",
    symbol: "AAVE",
    tf: "30m",
    side: "LONG",
    dataLabel: "19/02",
    stop: -2.6,
    alvo: 2.4,
    motivos: "-",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 9,
    mes: "FEV",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -0.618,
    alvo: 1,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 10,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "18/02",
    stop: -1.25,
    alvo: 2.4,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 11,
    mes: "FEV",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -1.45,
    alvo: 0.618,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 12,
    mes: "FEV",
    symbol: "UNI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "20/02",
    stop: -0.8,
    alvo: 1,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 13,
    mes: "FEV",
    symbol: "BTC",
    tf: "1h",
    side: "SHORT",
    dataLabel: "22/02",
    stop: -0.94,
    alvo: 9,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 14,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "22/02",
    stop: -2.4,
    alvo: -0.618,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 15,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.414,
    alvo: 0.618,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 16,
    mes: "FEV",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.06,
    alvo: 10,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 17,
    mes: "FEV",
    symbol: "LINK",
    tf: "15m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -1.2,
    alvo: 13.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(-25),
  },
  {
    id: 18,
    mes: "FEV",
    symbol: "ADA",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 19,
    mes: "FEV",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0.618,
    motivos: "-",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  // â€”â€” MarÃ§o inÃ­cio (planilha MARÃ‡O) â€”â€”
  {
    id: 20,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "01/03",
    stop: -1.87,
    alvo: 0.9,
    motivos: "FR/FO",
    conservador: S(0.63),
    mediano: S(1.14),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 21,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -1.83,
    alvo: 0.2,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 22,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.32,
    alvo: 0.7,
    motivos: "LSR",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 23,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.15,
    alvo: 0.7,
    motivos: "FR/FO",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 24,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "LONG",
    dataLabel: "01/03",
    stop: -2.48,
    alvo: 0.1,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 25,
    mes: "MAR",
    symbol: "BTC",
    tf: "4h",
    side: "SHORT",
    dataLabel: "02/03",
    stop: -0.618,
    alvo: 1.5,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 26,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.21,
    alvo: 1.3,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(-25),
  },
  {
    id: 27,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.19,
    alvo: -0.4,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 28,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "03/03",
    stop: -1.5,
    alvo: 2.4,
    motivos: "LE/HE",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 29,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "03/03",
    stop: -0.618,
    alvo: 2.2,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },

  {
    id: 30,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.59,
    alvo: 0.6,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 31,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -2.35,
    alvo: 0.9,
    motivos: "-",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 32,
    mes: "MAR",
    symbol: "BTC",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -2.05,
    alvo: -0.4,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 33,
    mes: "MAR",
    symbol: "AAVE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.32,
    alvo: 1.6,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 34,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -1.7,
    alvo: 1.0,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 35,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.7,
    alvo: 6.5,
    motivos: "FR/FO",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 36,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.8,
    alvo: 7.1,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 37,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "04/03",
    stop: -0.618,
    alvo: 5.4,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 38,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "04/03",
    stop: -2.48,
    alvo: -0.1,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 39,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "05/03",
    stop: -1.3,
    alvo: 1.6,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 40,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "SHORT",
    dataLabel: "05/03",
    stop: -0.7,
    alvo: 5.1,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(-25),
  },
  {
    id: 41,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.7,
    alvo: -0.6,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 42,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -0.618,
    alvo: 2.3,
    motivos: "LE/HE",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 43,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.414,
    alvo: -0.3,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 44,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "05/03",
    stop: -1.59,
    alvo: -0.5,
    motivos: "FR/FO",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 45,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -2.11,
    alvo: -0.5,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 46,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -1.52,
    alvo: 0,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 47,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -2.3,
    alvo: 1.5,
    motivos: "FR/FO",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 48,
    mes: "MAR",
    symbol: "LINK",
    tf: "30m",
    side: "LONG",
    dataLabel: "06/03",
    stop: -0.9,
    alvo: 0.5,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 49,
    mes: "MAR",
    symbol: "ADA",
    tf: "30m",
    side: "LONG",
    dataLabel: "07/03",
    stop: -4.2,
    alvo: -1.0,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 50,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "07/03",
    stop: -3.73,
    alvo: -0.6,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 51,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "07/03",
    stop: -1.82,
    alvo: 2.4,
    motivos: "-",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 52,
    mes: "MAR",
    symbol: "AAVE",
    tf: "30m",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.75,
    alvo: 1.0,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 53,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: -1.76,
    alvo: 0.8,
    motivos: "FR/FO",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 54,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.64,
    alvo: 0.7,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 55,
    mes: "MAR",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.64,
    alvo: 0.7,
    motivos: "FR/FO",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 56,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.63,
    alvo: 0.6,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 57,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.618,
    alvo: 3.7,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 58,
    mes: "MAR",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -1.15,
    alvo: 7.4,
    motivos: "FR/FO",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 59,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.9,
    alvo: 8.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 60,
    mes: "MAR",
    symbol: "BNB",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.9,
    alvo: 8.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 61,
    mes: "MAR",
    symbol: "ETH",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.9,
    alvo: 7.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 62,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.9,
    alvo: 7.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 63,
    mes: "MAR",
    symbol: "SOL",
    tf: "1h",
    side: "LONG",
    dataLabel: "08/03",
    stop: -0.9,
    alvo: 7.5,
    motivos: "LE/HE",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 64,
    mes: "MAR",
    symbol: "AVAX",
    tf: "15m",
    side: "LONG",
    dataLabel: "09/03",
    stop: -2.49,
    alvo: -0.2,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 65,
    mes: "MAR",
    symbol: "AAVE",
    tf: "4h",
    side: "LONG",
    dataLabel: "09/03",
    stop: -0.7,
    alvo: 3.5,
    motivos: "FR/FO",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 66,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "SHORT",
    dataLabel: "10/03",
    stop: -0.9,
    alvo: 2.3,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 67,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "10/03",
    stop: -2.35,
    alvo: 1.3,
    motivos: "LSR",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 68,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "10/03",
    stop: -0.7,
    alvo: 0.8,
    motivos: "LE/HE",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 69,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/03",
    stop: -1.86,
    alvo: 1.9,
    motivos: "LSR",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 70,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "11/03",
    stop: -0.7,
    alvo: 11.3,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 71,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -2.9,
    alvo: -0.6,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 72,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -1.075,
    alvo: 0.6,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 73,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -0.94,
    alvo: 1.5,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 74,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "11/03",
    stop: -0.618,
    alvo: 1.7,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },

  {
    id: 75,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -2.11,
    alvo: 0.6,
    motivos: "FR/FO",
    conservador: S(0.63),
    mediano: S(1.14),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 76,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -2.32,
    alvo: -0.8,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 77,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -3.42,
    alvo: 1.2,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 78,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -3.41,
    alvo: 1.2,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 79,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/03",
    stop: -5.6,
    alvo: 2.1,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 80,
    mes: "MAR",
    symbol: "XRP",
    tf: "30m",
    side: "SHORT",
    dataLabel: "13/03",
    stop: -2.75,
    alvo: 2.0,
    motivos: "LSR",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 81,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "14/03",
    stop: -1.38,
    alvo: 1.0,
    motivos: "FR/FO",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 82,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "15/03",
    stop: -1.32,
    alvo: 12.0,
    motivos: "LE/HE",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 83,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -7,
    alvo: null,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 84,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -6,
    alvo: null,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 85,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/03",
    stop: -10,
    alvo: null,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 86,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.72,
    alvo: 10.4,
    motivos: "LE/HE",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 87,
    mes: "MAR",
    symbol: "UNI",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.105,
    alvo: 4.7,
    motivos: "LE/HE",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 88,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -0.62,
    alvo: 0.6,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 89,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -13.3,
    alvo: null,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 90,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1.275,
    alvo: 3.4,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 91,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -2.035,
    alvo: 3.7,
    motivos: "LSR",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },

  {
    id: 92,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -4.7,
    alvo: 2.9,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 93,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -1,
    alvo: 12.3,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 94,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/03",
    stop: -2.04,
    alvo: 22.0,
    motivos: "LSR",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 95,
    mes: "MAR",
    symbol: "ADA",
    tf: "1h",
    side: "SHORT",
    dataLabel: "17/03",
    stop: -1.355,
    alvo: 5.8,
    motivos: "LE/HE",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 96,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: -2.79,
    alvo: -0.6,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 97,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: -1.475,
    alvo: 0.8,
    motivos: "FR/FO",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 98,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "17/03",
    stop: -2.45,
    alvo: -0.6,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 99,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "17/03",
    stop: -0.721,
    alvo: 4.8,
    motivos: "LSR",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 100,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "17/03",
    stop: -1.15,
    alvo: 0.6,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 101,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "SHORT",
    dataLabel: "18/03",
    stop: -2.178,
    alvo: 24.5,
    motivos: "FR/FO",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(36.17),
    degen: S(-25),
  },

  {
    id: 102,
    mes: "MAR",
    symbol: "LINK",
    tf: "30m",
    side: "LONG",
    dataLabel: "19/03",
    stop: -2.9,
    alvo: -0.8,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(7.14),
    agressivo: S(-25),
    degen: S(-1.95),
  },
  {
    id: 103,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/03",
    stop: -1.245,
    alvo: 1.2,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(-25),
  },
  {
    id: 104,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "19/03",
    stop: -1.018,
    alvo: 2.4,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 105,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "LONG",
    dataLabel: "19/03",
    stop: -1.115,
    alvo: 3.3,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 106,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "19/03",
    stop: -1.59,
    alvo: 5.1,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 107,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "19/03",
    stop: -4.95,
    alvo: 1.0,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 108,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "20/03",
    stop: -0.625,
    alvo: 3.1,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 109,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "20/03",
    stop: -1.066,
    alvo: 1.1,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 110,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "20/03",
    stop: -1.0688,
    alvo: 4.5,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },

  {
    id: 111,
    mes: "MAR",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -3.75,
    alvo: 8.4,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 112,
    mes: "MAR",
    symbol: "AVAX",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -3.23,
    alvo: 0.6,
    motivos: "FR/FO",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 113,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -3.06,
    alvo: 5.3,
    motivos: "LSR",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 114,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -3.81,
    alvo: 10.0,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 115,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -3.79,
    alvo: 4.3,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 116,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.34,
    alvo: 1.7,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 117,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1,
    alvo: 1.0,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },
  {
    id: 118,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.981,
    alvo: 1.6,
    motivos: "-",
    conservador: S(21.11),
    mediano: S(38.06),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 119,
    mes: "MAR",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.185,
    alvo: 4.8,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(-25),
  },
  {
    id: 120,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -0.78,
    alvo: 3.4,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 121,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -0.93,
    alvo: 5.0,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 122,
    mes: "MAR",
    symbol: "ETH",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.063,
    alvo: 3.4,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 123,
    mes: "MAR",
    symbol: "HYPE",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.77,
    alvo: 1.0,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 124,
    mes: "MAR",
    symbol: "XRP",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.456,
    alvo: 3.4,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 125,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.32,
    alvo: 4.1,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 126,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "LONG",
    dataLabel: "22/03",
    stop: -2.46,
    alvo: 2.6,
    motivos: "FR/FO",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 127,
    mes: "MAR",
    symbol: "BNB",
    tf: "1h",
    side: "LONG",
    dataLabel: "22/03",
    stop: -1.31,
    alvo: 4.1,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },

  {
    id: 128,
    mes: "MAR",
    symbol: "ADA",
    tf: "1h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -0.96,
    alvo: 7.7,
    motivos: "FR/FO",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 129,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -0.999,
    alvo: 7.2,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 130,
    mes: "MAR",
    symbol: "LINK",
    tf: "30m",
    side: "LONG",
    dataLabel: "23/03",
    stop: -0.999,
    alvo: 8.3,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },
  {
    id: 131,
    mes: "MAR",
    symbol: "XRP",
    tf: "1h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -1.045,
    alvo: 4.9,
    motivos: "-",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(204.15),
  },

  {
    id: 132,
    mes: "MAR",
    symbol: "AVAX",
    tf: "4h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -1.935,
    alvo: 0,
    motivos: "LE/HE",
    conservador: S(0.63),
    mediano: S(1.14),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 133,
    mes: "MAR",
    symbol: "BNB",
    tf: "4h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -2.61,
    alvo: 0,
    motivos: "LE/HE",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 134,
    mes: "MAR",
    symbol: "DOGE",
    tf: "4h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -1.31,
    alvo: 0,
    motivos: "LE/HE",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(-25),
  },
  {
    id: 135,
    mes: "MAR",
    symbol: "UNI",
    tf: "4h",
    side: "LONG",
    dataLabel: "23/03",
    stop: -2.94,
    alvo: 0,
    motivos: "LE/HE",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 136,
    mes: "MAR",
    symbol: "AVAX",
    tf: "30m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -1.899,
    alvo: 1.2,
    motivos: "-",
    conservador: S(0.63),
    mediano: S(1.14),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 137,
    mes: "MAR",
    symbol: "AAVE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -3.6,
    alvo: 32.0,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 138,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -3.075,
    alvo: 1.6,
    motivos: "FR/FO",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 139,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -1.16,
    alvo: 0.6,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(-25),
  },
  {
    id: 140,
    mes: "MAR",
    symbol: "SOL",
    tf: "15m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -1.175,
    alvo: 18.0,
    motivos: "LSR",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(-25),
  },
  {
    id: 141,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "25/03",
    stop: -1.389,
    alvo: 12.8,
    motivos: "LSR",
    conservador: S(31.14),
    mediano: S(56.08),
    agressivo: S(113.17),
    degen: S(-25),
  },

  {
    id: 142,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "26/03",
    stop: -10,
    alvo: null,
    motivos: "LE/HE",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 143,
    mes: "MAR",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "26/03",
    stop: -1.86,
    alvo: 1.9,
    motivos: "-",
    conservador: S(21.11),
    mediano: S(38.06),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 144,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "LONG",
    dataLabel: "26/03",
    stop: -1.69,
    alvo: 1.4,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 145,
    mes: "MAR",
    symbol: "HYPE",
    tf: "1h",
    side: "LONG",
    dataLabel: "26/03",
    stop: -1.69,
    alvo: 1.4,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 146,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "27/03",
    stop: -5,
    alvo: null,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 147,
    mes: "MAR",
    symbol: "LINK",
    tf: "30m",
    side: "LONG",
    dataLabel: "27/03",
    stop: -5,
    alvo: null,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 148,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "LONG",
    dataLabel: "27/03",
    stop: -5,
    alvo: null,
    motivos: "FR/FO",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 149,
    mes: "MAR",
    symbol: "UNI",
    tf: "30m",
    side: "LONG",
    dataLabel: "27/03",
    stop: -5,
    alvo: null,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 150,
    mes: "MAR",
    symbol: "XRP",
    tf: "1h",
    side: "LONG",
    dataLabel: "27/03",
    stop: -1.48,
    alvo: 0.9,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 151,
    mes: "MAR",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "28/03",
    stop: -3.07,
    alvo: 0.8,
    motivos: "LE/HE",
    conservador: S(0.63),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 152,
    mes: "MAR",
    symbol: "LINK",
    tf: "1h",
    side: "LONG",
    dataLabel: "28/03",
    stop: -2.91,
    alvo: 1.6,
    motivos: "LE/HE",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 153,
    mes: "MAR",
    symbol: "UNI",
    tf: "1h",
    side: "LONG",
    dataLabel: "28/03",
    stop: -2.95,
    alvo: 4.4,
    motivos: "LE/HE",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 154,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "29/03",
    stop: -1.201,
    alvo: 1.8,
    motivos: "FR/FO",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 155,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "29/03",
    stop: -1.815,
    alvo: 1.6,
    motivos: "-",
    conservador: S(21.11),
    mediano: S(38.06),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 156,
    mes: "MAR",
    symbol: "LINK",
    tf: "15m",
    side: "LONG",
    dataLabel: "29/03",
    stop: -1.605,
    alvo: 0.0,
    motivos: "LSR",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 157,
    mes: "MAR",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "29/03",
    stop: -2.61,
    alvo: 0.0,
    motivos: "-",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 158,
    mes: "MAR",
    symbol: "UNI",
    tf: "30m",
    side: "LONG",
    dataLabel: "29/03",
    stop: -1.21,
    alvo: 1.8,
    motivos: "-",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(-25),
  },
  {
    id: 159,
    mes: "MAR",
    symbol: "ADA",
    tf: "4h",
    side: "LONG",
    dataLabel: "29/03",
    stop: -0.88,
    alvo: 1.3,
    motivos: "-",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },

  {
    id: 160,
    mes: "MAR",
    symbol: "BNB",
    tf: "4h",
    side: "LONG",
    dataLabel: "30/03",
    stop: -2.11,
    alvo: 0,
    motivos: "LE/HE",
    conservador: S(21.11),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },
  {
    id: 161,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "SHORT",
    dataLabel: "30/03",
    stop: -0.81,
    alvo: 1.9,
    motivos: "LSR",
    conservador: S(12.72),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 162,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "LONG",
    dataLabel: "30/03",
    stop: -3.5,
    alvo: -1.3,
    motivos: "FR/FO",
    conservador: S(-25),
    mediano: S(-25),
    agressivo: S(-25),
    degen: S(-25),
  },

  {
    id: 163,
    mes: "MAR",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "31/03",
    stop: -0.81,
    alvo: 4.0,
    motivos: "LSR",
    conservador: S(31.14),
    mediano: S(25.23),
    agressivo: S(36.17),
    degen: S(68.16),
  },
  {
    id: 164,
    mes: "MAR",
    symbol: "AAVE",
    tf: "4h",
    side: "LONG",
    dataLabel: "31/03",
    stop: -0.65,
    alvo: 1.2,
    motivos: "LSR",
    conservador: S(0.56),
    mediano: S(0.6),
    agressivo: S(0.71),
    degen: S(0.68),
  },

];
