/**
 * Prova de resultados — dados espelhados da planilha (Fev + início Mar).
 * Linhas sem transcrição completa na conversa: símbolo vazio; edite aqui.
 */
import type {
  MesResultadoKey,
  ResumoDiario,
  ResumoEstrategia,
  ResumoMesConfig,
  ResultadoTrade,
  StrategyCol,
} from "./resultados-types";

export const RESULTADOS_META = {
  targetLossUsd: 25,
  dolarBrlFev: 5.2,
  dolarBrlMar: 5.2,
};

export const RESUMO_FEV: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 118.4, winRatePct: 78.95, ranking: 4, lucroBrl: 615.7 },
  { nome: "MEDIANO", lucroUsd: 209.09, winRatePct: 68.42, ranking: 3, lucroBrl: 1087.28 },
  { nome: "AGRESSIVO", lucroUsd: 450.79, winRatePct: 52.63, ranking: 2, lucroBrl: 2344.12 },
  { nome: "DEGEN", lucroUsd: 679.29, winRatePct: 42.11, ranking: 1, lucroBrl: 3532.31 },
];

export const RESUMO_MAR: ResumoEstrategia[] = [
  { nome: "CONSERVADOR", lucroUsd: 1016.59, winRatePct: 74.16, ranking: 4, lucroBrl: 5286.28 },
  { nome: "MEDIANO", lucroUsd: 1413.4, winRatePct: 60.67, ranking: 3, lucroBrl: 7349.68 },
  { nome: "AGRESSIVO", lucroUsd: 2567.83, winRatePct: 47.19, ranking: 2, lucroBrl: 13352.7 },
  { nome: "DEGEN", lucroUsd: 2951.1, winRatePct: 31.46, ranking: 1, lucroBrl: 15345.71 },
];

export const RESUMO_MAR_DIARIO: ResumoDiario[] = [
  { nome: "Conservador", diasPositivos: 17, diasNegativos: 10, winRateDiasPct: 63, mediaDiariaBrl: 182.29 },
  { nome: "Mediano", diasPositivos: 19, diasNegativos: 8, winRateDiasPct: 70, mediaDiariaBrl: 253.44 },
  { nome: "Agressivo", diasPositivos: 16, diasNegativos: 11, winRateDiasPct: 59, mediaDiariaBrl: 460.44 },
  { nome: "Degen", diasPositivos: 14, diasNegativos: 13, winRateDiasPct: 52, mediaDiariaBrl: 529.16 },
];

/** Mês mais recente primeiro (selector na página de resultados). */
export const MESES_RESULTADO_ORDEM: MesResultadoKey[] = ["MAR", "FEV"];

export const ROTULO_MES: Record<MesResultadoKey, string> = {
  FEV: "Fevereiro",
  MAR: "Março",
};

export const RESUMO_POR_MES: Record<MesResultadoKey, ResumoMesConfig> = {
  FEV: {
    estrategias: RESUMO_FEV,
    footerTexto:
      "Média das estratégias (Fev): ~US$ 364,39 · Win rate médio ~60,53% · Média 30 dias US$ 910,99 · Média diária ~US$ 30,37 (~R$ 157,90).",
  },
  MAR: {
    estrategias: RESUMO_MAR,
    footerTexto:
      "Média (Mar): US$ 1.987,23 · Win rate médio 53,37% · Média 30 dias US$ 2.055,75 · Média diária US$ 68,53 (~R$ 356,33).",
    diario: RESUMO_MAR_DIARIO,
  },
};

const S = (hit: StrategyCol["hit"], pnlUsd: number | null): StrategyCol => ({ hit, pnlUsd });

const allStop25 = (): Pick<
  ResultadoTrade,
  "conservador" | "mediano" | "agressivo" | "degen"
> => ({
  conservador: S("STOP", -25),
  mediano: S("STOP", -25),
  agressivo: S("STOP", -25),
  degen: S("STOP", -25),
});

const vazio: Pick<ResultadoTrade, "conservador" | "mediano" | "agressivo" | "degen"> = {
  conservador: null,
  mediano: null,
  agressivo: null,
  degen: null,
};

/** Linha a preencher (trecho da planilha não transcrito). */
function pendente(
  id: number,
  mes: "FEV" | "MAR",
  dataLabel: string,
): ResultadoTrade {
  return {
    id,
    mes,
    symbol: "",
    tf: "",
    side: "LONG",
    dataLabel,
    stop: null,
    alvo: null,
    motivos: "—",
    filtro100: false,
    ...vazio,
  };
}

export const RESULTADOS_TRADES: ResultadoTrade[] = [
  // —— Fevereiro (planilha FEVEREIRO) ——
  {
    id: 1,
    mes: "FEV",
    symbol: "ETH",
    tf: "15m",
    side: "LONG",
    dataLabel: "09/02",
    stop: -1.95,
    alvo: 0,
    motivos: "-",
    filtro100: true,
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 2,
    mes: "FEV",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "10/02",
    stop: -1.51,
    alvo: 0,
    motivos: "-",
    filtro100: true,
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 3,
    mes: "FEV",
    symbol: "BTC",
    tf: "30m",
    side: "SHORT",
    dataLabel: "21/02",
    stop: -0.95,
    alvo: 3,
    motivos: "-",
    filtro100: true,
    conservador: S("2", 12.72),
    mediano: S("2", 25.23),
    agressivo: S("2", 36.17),
    degen: S("2", 68.16),
  },
  {
    id: 4,
    mes: "FEV",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 18,
    motivos: "-",
    filtro100: true,
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 5,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "12/02",
    stop: -1.05,
    alvo: 18,
    motivos: "-",
    filtro100: true,
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 6,
    mes: "FEV",
    symbol: "BTC",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/02",
    stop: -0.618,
    alvo: 1.618,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 7,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "13/02",
    stop: -1.5,
    alvo: 0.618,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 8,
    mes: "FEV",
    symbol: "AAVE",
    tf: "30m",
    side: "LONG",
    dataLabel: "19/02",
    stop: -2.6,
    alvo: 2.4,
    motivos: "-",
    filtro100: true,
    conservador: S("2", 21.11),
    mediano: S("STOP", -25),
    agressivo: S("2", 36.17),
    degen: S("STOP", -25),
  },
  {
    id: 9,
    mes: "FEV",
    symbol: "AAVE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -0.618,
    alvo: 1,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("1", 0.71),
    degen: S("1", 0.68),
  },
  {
    id: 10,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "18/02",
    stop: -1.25,
    alvo: 2.4,
    motivos: "-",
    filtro100: true,
    conservador: S("2", 12.72),
    mediano: S("2", 25.23),
    agressivo: S("2", 36.17),
    degen: S("STOP", -25),
  },
  {
    id: 11,
    mes: "FEV",
    symbol: "DOGE",
    tf: "1h",
    side: "LONG",
    dataLabel: "19/02",
    stop: -1.45,
    alvo: 0.618,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 12,
    mes: "FEV",
    symbol: "UNI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "20/02",
    stop: -0.8,
    alvo: 1,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("1", 0.71),
    degen: S("1", 0.68),
  },
  {
    id: 13,
    mes: "FEV",
    symbol: "BTC",
    tf: "1h",
    side: "SHORT",
    dataLabel: "22/02",
    stop: -0.94,
    alvo: 9,
    motivos: "-",
    filtro100: true,
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 14,
    mes: "FEV",
    symbol: "HYPE",
    tf: "15m",
    side: "LONG",
    dataLabel: "22/02",
    stop: -2.4,
    alvo: -0.618,
    motivos: "-",
    filtro100: true,
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 15,
    mes: "FEV",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.414,
    alvo: 0.618,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.56),
    mediano: S("1", 0.6),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 16,
    mes: "FEV",
    symbol: "SOL",
    tf: "15m",
    side: "LONG",
    dataLabel: "24/02",
    stop: -1.06,
    alvo: 10,
    motivos: "-",
    filtro100: true,
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("3", 204.15),
  },
  {
    id: 17,
    mes: "FEV",
    symbol: "LINK",
    tf: "15m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -1.2,
    alvo: 13.5,
    motivos: "-",
    filtro100: true,
    conservador: S("3", 31.14),
    mediano: S("3", 56.08),
    agressivo: S("3", 113.17),
    degen: S("STOP", -25),
  },
  {
    id: 18,
    mes: "FEV",
    symbol: "ADA",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0,
    motivos: "-",
    filtro100: true,
    conservador: S("STOP", -25),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },
  {
    id: 19,
    mes: "FEV",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "28/02",
    stop: -2.4,
    alvo: 0.618,
    motivos: "-",
    filtro100: true,
    conservador: S("1", 0.63),
    mediano: S("STOP", -25),
    agressivo: S("STOP", -25),
    degen: S("STOP", -25),
  },

  // —— Março início (planilha MARÇO) ——
  {
    id: 20,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "LONG",
    dataLabel: "1/3",
    stop: -1.87,
    alvo: 0.9,
    motivos: "FR/FO",
    filtro100: false,
    ...vazio,
  },
  {
    id: 21,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "1/3",
    stop: -1.83,
    alvo: 0.2,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 22,
    mes: "MAR",
    symbol: "SUI",
    tf: "15m",
    side: "LONG",
    dataLabel: "1/3",
    stop: -2.32,
    alvo: 0.7,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 23,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "1/3",
    stop: -2.15,
    alvo: 0.7,
    motivos: "FR/FO",
    filtro100: false,
    ...vazio,
  },
  {
    id: 24,
    mes: "MAR",
    symbol: "BNB",
    tf: "15m",
    side: "LONG",
    dataLabel: "1/3",
    stop: -2.48,
    alvo: 0.1,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 25,
    mes: "MAR",
    symbol: "BTC",
    tf: "4h",
    side: "SHORT",
    dataLabel: "2/3",
    stop: -0.618,
    alvo: 1.5,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 26,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "LONG",
    dataLabel: "3/3",
    stop: -1.21,
    alvo: 1.3,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 27,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "LONG",
    dataLabel: "3/3",
    stop: -1.19,
    alvo: -0.4,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 28,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "LONG",
    dataLabel: "3/3",
    stop: -1.5,
    alvo: 2.4,
    motivos: "LE/HE",
    filtro100: false,
    ...vazio,
  },
  {
    id: 29,
    mes: "MAR",
    symbol: "AVAX",
    tf: "1h",
    side: "LONG",
    dataLabel: "3/3",
    stop: -0.618,
    alvo: 2.2,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },

  // 30–50: preencher a partir da planilha (trecho não transcrito)
  pendente(30, "MAR", "4/3"),
  pendente(31, "MAR", "4/3"),
  pendente(32, "MAR", "5/3"),
  pendente(33, "MAR", "5/3"),
  pendente(34, "MAR", "5/3"),
  pendente(35, "MAR", "6/3"),
  pendente(36, "MAR", "6/3"),
  pendente(37, "MAR", "7/3"),
  pendente(38, "MAR", "7/3"),
  pendente(39, "MAR", "8/3"),
  pendente(40, "MAR", "8/3"),
  pendente(41, "MAR", "9/3"),
  pendente(42, "MAR", "9/3"),
  pendente(43, "MAR", "9/3"),
  pendente(44, "MAR", "10/3"),
  pendente(45, "MAR", "10/3"),
  pendente(46, "MAR", "10/3"),
  pendente(47, "MAR", "10/3"),
  pendente(48, "MAR", "10/3"),
  pendente(49, "MAR", "10/3"),
  pendente(50, "MAR", "10/3"),

  // 51–54 (planilha)
  {
    id: 51,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "LONG",
    dataLabel: "5/3",
    stop: null,
    alvo: null,
    motivos: "LE/HE",
    filtro100: false,
    ...allStop25(),
  },
  {
    id: 52,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "5/3",
    stop: null,
    alvo: null,
    motivos: "FR/FO",
    filtro100: false,
    ...allStop25(),
  },
  {
    id: 53,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "LONG",
    dataLabel: "6/3",
    stop: null,
    alvo: null,
    motivos: "LE/HE",
    filtro100: false,
    ...allStop25(),
  },
  {
    id: 54,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "6/3",
    stop: null,
    alvo: null,
    motivos: "-",
    filtro100: true,
    ...allStop25(),
  },

  pendente(55, "MAR", "7/3"),
  pendente(56, "MAR", "7/3"),
  pendente(57, "MAR", "8/3"),
  pendente(58, "MAR", "8/3"),
  pendente(59, "MAR", "8/3"),
  pendente(60, "MAR", "9/3"),
  pendente(61, "MAR", "9/3"),
  pendente(62, "MAR", "9/3"),
  pendente(63, "MAR", "9/3"),
  pendente(64, "MAR", "10/3"),
  pendente(65, "MAR", "10/3"),
  pendente(66, "MAR", "10/3"),
  pendente(67, "MAR", "10/3"),
  pendente(68, "MAR", "10/3"),
  pendente(69, "MAR", "10/3"),
  pendente(70, "MAR", "10/3"),
  pendente(71, "MAR", "10/3"),
  pendente(72, "MAR", "10/3"),
  pendente(73, "MAR", "10/3"),
  pendente(74, "MAR", "10/3"),
  pendente(75, "MAR", "10/3"),

  {
    id: 76,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "10/3",
    stop: -0.7,
    alvo: 0.8,
    motivos: "LE/HE",
    filtro100: false,
    ...vazio,
  },
  {
    id: 77,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "LONG",
    dataLabel: "11/3",
    stop: -1.86,
    alvo: 1.9,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 78,
    mes: "MAR",
    symbol: "ETH",
    tf: "30m",
    side: "LONG",
    dataLabel: "11/3",
    stop: -0.7,
    alvo: 11.3,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 79,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/3",
    stop: -2.9,
    alvo: -0.6,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 80,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/3",
    stop: -1.075,
    alvo: 0.6,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 81,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "11/3",
    stop: -0.94,
    alvo: 1.5,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 82,
    mes: "MAR",
    symbol: "HYPE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "11/3",
    stop: -0.618,
    alvo: 1.7,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 83,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/3",
    stop: -2.11,
    alvo: 0.6,
    motivos: "FR/FO",
    filtro100: false,
    ...vazio,
  },
  {
    id: 84,
    mes: "MAR",
    symbol: "ETH",
    tf: "15m",
    side: "SHORT",
    dataLabel: "12/3",
    stop: -2.32,
    alvo: -0.8,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 85,
    mes: "MAR",
    symbol: "BNB",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/3",
    stop: -3.42,
    alvo: 1.2,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 86,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/3",
    stop: -3.41,
    alvo: 1.2,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 87,
    mes: "MAR",
    symbol: "DOGE",
    tf: "30m",
    side: "SHORT",
    dataLabel: "12/3",
    stop: -5.6,
    alvo: 2.1,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 88,
    mes: "MAR",
    symbol: "XRP",
    tf: "30m",
    side: "SHORT",
    dataLabel: "13/3",
    stop: -2.75,
    alvo: 2.0,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 89,
    mes: "MAR",
    symbol: "SUI",
    tf: "30m",
    side: "LONG",
    dataLabel: "14/3",
    stop: -1.38,
    alvo: 1.0,
    motivos: "FR/FO",
    filtro100: false,
    ...vazio,
  },
  {
    id: 90,
    mes: "MAR",
    symbol: "ADA",
    tf: "15m",
    side: "LONG",
    dataLabel: "15/3",
    stop: -1.32,
    alvo: 12.0,
    motivos: "LE/HE",
    filtro100: false,
    ...vazio,
  },
  {
    id: 91,
    mes: "MAR",
    symbol: "AAVE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/3",
    stop: -7,
    alvo: null,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 92,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/3",
    stop: -6,
    alvo: null,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 93,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "15/3",
    stop: -10,
    alvo: null,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 94,
    mes: "MAR",
    symbol: "UNI",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -1.72,
    alvo: 10.4,
    motivos: "LE/HE",
    filtro100: false,
    ...vazio,
  },
  {
    id: 95,
    mes: "MAR",
    symbol: "UNI",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -1.105,
    alvo: 4.7,
    motivos: "LE/HE",
    filtro100: false,
    ...vazio,
  },
  {
    id: 96,
    mes: "MAR",
    symbol: "SOL",
    tf: "30m",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -0.62,
    alvo: 0.6,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 97,
    mes: "MAR",
    symbol: "XRP",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -13.3,
    alvo: null,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },
  {
    id: 98,
    mes: "MAR",
    symbol: "DOGE",
    tf: "1h",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -1.275,
    alvo: 3.4,
    motivos: "-",
    filtro100: true,
    ...vazio,
  },
  {
    id: 99,
    mes: "MAR",
    symbol: "DOGE",
    tf: "15m",
    side: "SHORT",
    dataLabel: "16/3",
    stop: -2.035,
    alvo: 3.7,
    motivos: "LSR",
    filtro100: false,
    ...vazio,
  },

  pendente(100, "MAR", "16/3"),
];
